server:
  port: 8250

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: armelo
    password: armelo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.group.lusi.dev.ecommerce.order.kafka.OrderConfirmation


application:
  config:
    customer-url: http://localhost:9000/api/v1/customers
    product-url: http://localhost:9000/api/v1/products
    payment-url: http://localhost:9000/api/v1/payments
